In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("Data\Airline Loyalty Data Dictionary.csv")
df2 = pd.read_csv("Data\Customer Flight Activity.csv")
df3 = pd.read_csv("Data\Customer Loyalty History.csv")
df4 = pd.read_csv("Data\Calendar.csv")

In [ ]:
df1

,Table,Field,Description
0,Customer Flight Activity,Loyalty Number,Customer's unique loyalty number
1,NaN,Year,Year of the period
2,NaN,Month,Month of the period
3,NaN,Total Flights,Sum of Flights Booked (all tickets purchased i...
4,NaN,Distance,Flight distance traveled in the period (km)
5,NaN,Points Accumulated,Loyalty points accumulated in the period
6,NaN,Points Redeemed,Loyalty points redeemed in the period
7,NaN,Dollar Cost Points Redeemed,Dollar equivalent for points redeemed in the p...
8,Customer Loyalty History,Loyalty Number,Customer's unique loyalty number
9,NaN,Country,Country of residence
10,NaN,Province,Province of residence
11,NaN,City,City of residence
12,NaN,Postal Code,Postal code of residence
13,NaN,Gender,Gender
14,NaN,Education,Highest education level (High school or lower ...
15,NaN,Salary,Annual income
16,NaN,Marital Status,"Marital status (Single, Married, Divorced)"
17,NaN,Loyalty Card,Loyalty card status (Star > Nova > Aurora)
18,NaN,CLV,Customer lifetime value - total invoice value ...
19,NaN,Enrollment Type,Enrollment type (Standard / 2018 Promotion)
20,NaN,Enrollment Year,Year Member enrolled in membership program
21,NaN,Enrollment Month,Month Member enrolled in membership program
22,NaN,Cancellation Year,Year Member cancelled their membership
23,NaN,Cancellation Month,Month Member cancelled their membership

In [5]:
df2.head()

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100590,2018,6,12,15276,22914.0,0,0
1,100590,2018,7,12,9168,13752.0,0,0
2,100590,2018,5,4,6504,9756.0,0,0
3,100590,2018,10,0,0,0.0,512,92
4,100590,2018,2,0,0,0.0,0,0

In [20]:
check = df2.loc[df2['Loyalty Number'] == 100590].sort_values(by=['Year', 'Month'], ascending=[True, True])
check

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
4,100590,2018,2,0,0,0.0,0,0
6,100590,2018,3,0,0,0.0,0,0
5,100590,2018,4,0,0,0.0,0,0
2,100590,2018,5,4,6504,9756.0,0,0
0,100590,2018,6,12,15276,22914.0,0,0
1,100590,2018,7,12,9168,13752.0,0,0
7,100590,2018,8,0,0,0.0,0,0
8,100590,2018,9,0,0,0.0,0,0
3,100590,2018,10,0,0,0.0,512,92
9,100590,2018,11,0,0,0.0,0,0
10,100590,2018,12,0,0,0.0,0,0

In [7]:
borders = [df4['Date'].min(), df4['Date'].max()]
borders

['2012-01-01', '2018-12-31']

In [9]:
df2['Year'].value_counts()

Year
2018    201836
2017    191100
Name: count, dtype: int64

In [11]:
df2['Loyalty Number'].nunique()

16737

In [12]:
df3['Loyalty Number'].nunique()

16737

In [22]:
df3.loc[df3['Loyalty Number'] == 100590, 'CLV']

5754    34090.04
Name: CLV, dtype: float64

In [7]:
df3.shape

(16737, 16)

In [9]:
df2['Loyalty Number'].nunique()

16737

In [10]:
df2.shape

(392936, 8)

In [17]:
df3.head()

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [19]:
df3['Enrollment Type'].value_counts()

Enrollment Type
Standard          15766
2018 Promotion      971
Name: count, dtype: int64

In [23]:
df3.loc[df3['Cancellation Month'].isna(), 'Cancellation Year'].nunique()

0

In [29]:
df3['Salary'].dtype

dtype('float64')

In [27]:
df2['Year'].value_counts()

Year
2018    201836
2017    191100
Name: count, dtype: int64